### ISSUE TITLE
Running examples doesn't drag properly

### ISSUE THREAD

**Issue by AndrewRayCode** [gre/bezier-easing-editor#3] opened 2015-09-21 22:04 UTC
after installing and running `npm run start` in `example/` and going to http://localhost:9966/ the page and script both load but when trying to drag a handle the mouse just disappears and the handle doesn't move.

**Comment by gre** [comment] 2015-09-22 12:55
this seems to be a regression introduced by https://github.com/gre/bezier-easing-editor/pull/1

My guess is that babel is not correctly compiling the files.

I think I'll revert this.. I don't like the fact that the library have to preprocess on its own. This should be fixed at the user level (browserify / webpack).

**Comment by gre** [comment] 2015-09-22 13:01
Ok I was wrong, this is weird. I don't know where the bug is.

**Comment by gre** [comment] 2015-09-22 13:14
Ok. this is fixed in master & in new release 0.4.6.

this was related to an old version of babel, and the fact that babel was implicit (using global install) was a breaking change.
I keep thinking a simplification for the build is better, so see instruction in the [commit](https://github.com/gre/bezier-easing-editor/commit/6c65e27b02f085388ff1235bc9f464d0378639c8) if you are stuck with  this.

**Closed as completed by gre** 2015-09-22 13:14 UTC
